# Generated by Django 4.0.5 on 2022-09-15 11:11

from django.db import migrations, models
import uuid


def forwards_func(apps, schema_editor):
    Team = apps.get_model("core_base", "Team")
    for obj in Team.objects.all():
        obj.uuid_hash = uuid.uuid4()
        obj.save()


def reverse_func(apps, schema_editor):
    Team = apps.get_model("core_base", "Team")
    Team.objects.update(uuid_hash=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='uuid_hash',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='team',
            name='uuid_hash',
            field=models.UUIDField(null=False, default=uuid.uuid4, unique=True),
        ),
    ]
