# Generated by Django 4.0.5 on 2022-09-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0004_remove_participant_team_remove_team_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='team_uuid',
            field=models.ForeignKey(db_column='team_uuid', on_delete=django.db.models.deletion.CASCADE, to='core_base.team'),
        ),
    ]
