# Generated by Django 4.0.5 on 2022-09-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_base', '0005_alter_participant_team_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='team_uuid',
            new_name='team',
        ),
    ]
